### ISSUE TITLE
Create a Kubernetes deployment

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-reportserver#5]

**Comment by iperdomo** [comment]
Missing pieces to have an automated deployment
- [ ] Grab the service account to interact with the k8s cluster (store it as encrypted file)
- [ ] After a sucessful `docker push` we need to modify `deployment.yaml` to match the new version sha
- [ ] As part of `deploy.sh` we need to activate the service account
- [ ] We can call `kubectl apply -f ci/k8s/deployment.yaml` to update the deployment

**Comment by iperdomo** [comment]
@stellanl 

When building the Docker image, we can `unzip` the content of the ReportServer webapp as `${CATALINA_HOME}/webapps/ROOT` instead of `{CATALINA_HOME}/webapps/reportserver` so we don't need to setup any http redirect from root to reportserver: `/ -> /reportserver/`.

I understand that this makes a change in the integration with RSR (the lack of `/reportserver/` path), but we're changing host anyway and we can just remove that.

See this changeset:
https://github.com/akvo/akvo-reportserver/commit/a702e190c0cf5cf5b7988746fc5f706b3de6382f#diff-3254677a7917c6c01f55212f86c57fbfR18
